### ISSUE TITLE
Seems to no longer work

### ISSUE THREAD

**Issue by ChrisMBarr** [Shantaks/photoreflect-password-recovery#1]
It appears they are no longer storing the password in the viewstate. I ran your script and got the "Password Recovery Failed!" message.

Visiting a password protected gallery page, I was able to run this in the browser console to base64 decode the view state to see what was in there

```js
atob(document.getElementById("__VIEWSTATE").value)
```

Manually inspecting the data there shows that there seems to be no "ChallengePass" in there 😞

**Comment by jonesmusic8** [comment]
Hi did you ever get it to work?

**Comment by ChrisMBarr** [comment]
I haven't tried it again since then, but it appears they have changed their website so that this data is no longer stored in the viewstate.
